FROM apache/superset

RUN \
  superset fab create-admin \
      --username admin \
      --firstname Superset \
      --lastname Admin \
      --email admin@admin.com \
      --password postgres123; \
  superset db upgrade; \
  pip install clickhouse-connect; \
  superset init;
